import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { BottomNavbar, Header, Sidebar } from "./components";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="min-h-screen bg-customcolors-darkblue text-white">
          <Header />
            <div className="m-0 p-0 md:mx-auto md:px-4 md:container md:py-6 flex">
            <Sidebar />
            <main className="flex-1 p-0 mb-[80px] md:mb-0 md:p-5 overflow-x-hidden">{children}</main>
            <BottomNavbar />
            </div>
        </div>
      </body>
    </html>
  );
}
